### ISSUE TITLE
TimPicker not working as expected with maxTime and minTime

### ISSUE THREAD

**Issue by TheVaan** [Vuepic/vue3-date-time-picker#56]
**Describe the bug**
minTime prevents choosing a lower minute then minTime.minutes when the hour is higher then minTime.hours is. Same with maxTime: I can't select all minutes when hour is lower then maxTime.hours.
Maybe this is made by design, but for me "minTime - Sets the minimal available time to pick" means: this represents the lowest time you can choose, where minutes and hours combined(!) are the limit and not "lowest hour and independent lowest minute".
Furthermore using maxTime creates an effect of changing value as described in #38. I'm not using @update so I'm not sure why this happens.

**To Reproduce**
Set minTime and maxTime.
https://codesandbox.io/s/vue3-date-time-picker-demo-forked-31cce?file=/src/components/Demo.vue

**Expected behavior**
minTime: when an higher hour then minTime.hours is set, there is no limit for the minutes.
maxTime: when a lower hour then maxTime.hours is set, there is no limit for the minutes.
The time should not change when clicking inside the input.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome (96.0.4664.55), Safari (15.1)

**Comment by Jasenkoo** [comment]
It is a bug, will be fixed, not indeed by the design

**Comment by Jasenkoo** [comment]
@TheVaan Sorry, I misunderstood what was happening. Explained behavior is OK since you don't configure the actual time here for example `7:10`, but rather `7` being the min selectable hours and `10` min selectable minutes. The same applies to the `maxTime`.

Regarding the issue with time jumping, this is happening when the current time is higher/lower than the actual defined max and min. This was set up by the design since you wouldn't be able to add/subtract hours/minutes if the browser time is not in the defined range.

Anyway, I will make some adjustments so that min and max can be configured as times, and for the time-jumping, I will check what can be done there.

**Comment by TheVaan** [comment]
Thank you for your quick reply! I already thought that this was meant as an limit for each value.
It's a special use case in my project. 🙈

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents

**Comment by TheVaan** [comment]
Thank you! I found a small bug with maxTime. I checked your code and it looks fine, so I don't get it...

Take a look here: https://codesandbox.io/s/vue3-date-time-picker-demo-forked-31cce?file=/src/components/Demo.vue
When reaching "max hour" I can go one step further to "max.hours + 1" while min is working correctly.

E.g.: max hours = 10, 11 is selectable, 12 isn't.

**Comment by Jasenkoo** [comment]
Fix [v2.4.1](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.1) is now live, it should work correctly now
